AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  GetCustomersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/app.getCustomersHandler
      # CodeUri: src
      Role: "arn:aws:iam::989986469110:role/lambdaAPI"
      Runtime: nodejs14.x
      Description: Get all customers
      MemorySize: 128
      Timeout: 3
      Events:
        GetAllCustomers:
          Type: Api
          Properties:
            Path: /customers
            Method: get

  GetCustomerByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/app.getCustomerByIdHandler
      Role: "arn:aws:iam::989986469110:role/lambdaAPI"
      Runtime: nodejs14.x
      Description: Get customer by id
      MemorySize: 128
      Timeout: 3
      Events:
        GetCustomerById:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: get

  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/app.createCustomerHandler
      Role: "arn:aws:iam::989986469110:role/lambdaAPI"
      Runtime: nodejs14.x
      Description: Create customer
      MemorySize: 128
      Timeout: 3
      Events:
        CreateCustomer:
          Type: Api
          Properties:
            Path: /customers
            Method: post

  CreateCustomersFromCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/app.createCustomersFromCSVHandler
      Role: "arn:aws:iam::989986469110:role/lambdaAPI"
      Runtime: nodejs14.x
      Description: Create customers from CSV
      MemorySize: 128
      Timeout: 3
      Events:
        CreateCustomer:
          Type: Api
          Properties:
            Path: /customers/upload
            Method: post

  UpdateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/app.updateCustomerByIdHandler
      Role: "arn:aws:iam::989986469110:role/lambdaAPI"
      Runtime: nodejs14.x
      Description: Update customer
      MemorySize: 128
      Timeout: 3
      Events:
        UpdateCustomer:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: put

    # Metadata: # Manage esbuild properties
    #   BuildMethod: esbuild
    #   BuildProperties:
    #     Minify: true
    #     Target: "es2020"
    #     # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
    #     # EntryPoints:
    #     # - src/app.ts

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customers"
